### ISSUE TITLE
报错 

### ISSUE THREAD

**Issue by Mrwangfan** [fengjiel/vue-pagination#1]
1、点击的时候  报 Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "current"
怎么解决  谢谢！
@fengjiel

**Comment by fengjiel** [comment]
vue2限制了对props数据地直接操作，已修正，更改为传入对象更改对象属性 @Mrwangfan  多谢
